version: '3'
#https://imasters.com.br/devsecops/clusterizando-rabbitmq-com-docker-compose

services:

  rabbitmq1:
    image: samuelrac/rabbitmq-cluster:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    restart: always
    ports:
        - "0.0.0.0:10001:15672"
    networks:
        - rabbitmq
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      placement:
        constraints: 
          - "node.role == manager"
      resources:
        limits:
          memory: 2560M
        reservations:
          memory: 2048M
    volumes:
        - rabbitmq1:/var/lib/rabbitmq
    env_file: 
        - "rabbitmq.env"
 
  rabbitmq2:
    image: samuelrac/rabbitmq-cluster:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    restart: always
    ports:
        - "0.0.0.0:10002:15672"
    networks:
        - rabbitmq
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      placement:
        constraints: 
          - "node.role == worker"
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
    volumes:
        - rabbitmq2:/var/lib/rabbitmq
    env_file: 
        - "rabbitmq.env"
    depends_on:
        - rabbitmq1
 
  rabbitmq3:
    image: samuelrac/rabbitmq-cluster:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    restart: always
    ports:
        - "0.0.0.0:10003:15672"
    networks:
        - rabbitmq
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      placement:
        constraints: 
          - "node.role == worker"
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
    volumes:
        - rabbitmq3:/var/lib/rabbitmq
    env_file: 
        - "rabbitmq.env"
    depends_on:
        - rabbitmq1
 
  rabbitmq4:
    image: samuelrac/rabbitmq-cluster:3-management
    container_name: rabbitmq4
    hostname: rabbitmq4
    restart: always
    ports:
        - "0.0.0.0:10004:15672"
    networks:
        - rabbitmq
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      placement:
        constraints: 
          - "node.role == worker"
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
    volumes:
        - rabbitmq4:/var/lib/rabbitmq
    env_file: 
        - "rabbitmq.env"
    depends_on:
        - rabbitmq1
 
  rabbitmq-endpoint:
    image: samuelrac/haproxy-for-rabbitmq:1.6
    container_name: rabbitmq-endpoint
    hostname: rabbitmq-endpoint
    restart: always
    ports:
        - "0.0.0.0:5672:5672"
        - "0.0.0.0:10000:20000"
    networks:
        - rabbitmq
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      placement:
        constraints: 
          - "node.role == worker"
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
    links:
        - rabbitmq1:rabbitmq1
        - rabbitmq2:rabbitmq2
        - rabbitmq3:rabbitmq3
        - rabbitmq4:rabbitmq4

volumes: 
    rabbitmq1:
    rabbitmq2:
    rabbitmq3:
    rabbitmq4:

networks: 
    rabbitmq: